/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MGCRecord {
  'id' : string,
  'status' : string,
  'gearName' : string,
  'gearNo' : string,
  'gearType' : string,
  'partSerialNo' : string,
  'machineNo' : string,
  'dueDate' : string,
  'calibrationDate' : string,
  'remarks' : string,
}
export interface MachinePart { 'status' : string, 'name' : string }
export interface MachineRecord {
  'id' : string,
  'dueDate' : string,
  'doneDate' : string,
  'parts' : Array<MachinePart>,
  'machineNo' : string,
  'machineType' : string,
}
export interface _SERVICE {
  'addMGCRecord' : ActorMethod<
    [string, string, string, string, string, string, string, string, string, string],
    undefined
  >,
  'addMachine' : ActorMethod<
    [string, string, string, string, string, Array<MachinePart>],
    undefined
  >,
  'deleteMGCRecord' : ActorMethod<[string], undefined>,
  'deleteMachine' : ActorMethod<[string], undefined>,
  'getAllMGCRecords' : ActorMethod<[], Array<MGCRecord>>,
  'getAllMachines' : ActorMethod<[], Array<MachineRecord>>,
  'updateMGCRecord' : ActorMethod<
    [string, string, string, string, string, string, string, string, string, string],
    undefined
  >,
  'updateMachine' : ActorMethod<
    [string, string, string, Array<MachinePart>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
