/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MachinePart = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
});
export const MGCRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'gearName' : IDL.Text,
  'dueDate' : IDL.Text,
  'calibrationDate' : IDL.Text,
  'gearNo' : IDL.Text,
  'remarks' : IDL.Text,
});
export const MachineRecord = IDL.Record({
  'id' : IDL.Text,
  'dueDate' : IDL.Text,
  'doneDate' : IDL.Text,
  'parts' : IDL.Vec(MachinePart),
  'machineNo' : IDL.Text,
  'machineType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMGCRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(MachinePart)],
      [],
      [],
    ),
  'deleteMGCRecord' : IDL.Func([IDL.Text], [], []),
  'deleteMachine' : IDL.Func([IDL.Text], [], []),
  'getAllMGCRecords' : IDL.Func([], [IDL.Vec(MGCRecord)], ['query']),
  'getAllMachines' : IDL.Func([], [IDL.Vec(MachineRecord)], ['query']),
  'updateMGCRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMachine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(MachinePart)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MachinePart = IDL.Record({ 'status' : IDL.Text, 'name' : IDL.Text });
  const MGCRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'gearName' : IDL.Text,
    'dueDate' : IDL.Text,
    'calibrationDate' : IDL.Text,
    'gearNo' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const MachineRecord = IDL.Record({
    'id' : IDL.Text,
    'dueDate' : IDL.Text,
    'doneDate' : IDL.Text,
    'parts' : IDL.Vec(MachinePart),
    'machineNo' : IDL.Text,
    'machineType' : IDL.Text,
  });
  
  return IDL.Service({
    'addMGCRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addMachine' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(MachinePart),
        ],
        [],
        [],
      ),
    'deleteMGCRecord' : IDL.Func([IDL.Text], [], []),
    'deleteMachine' : IDL.Func([IDL.Text], [], []),
    'getAllMGCRecords' : IDL.Func([], [IDL.Vec(MGCRecord)], ['query']),
    'getAllMachines' : IDL.Func([], [IDL.Vec(MachineRecord)], ['query']),
    'updateMGCRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMachine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(MachinePart)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };