/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecordId = IDL.Text;
export const Category = IDL.Variant({
  'hr' : IDL.Null,
  'finance' : IDL.Null,
  'other' : IDL.Null,
  'sales' : IDL.Null,
  'operations' : IDL.Null,
});
export const CompanyRecord = IDL.Record({
  'id' : RecordId,
  'value' : IDL.Float64,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'category' : Category,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'deleteRecord' : IDL.Func([RecordId], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(CompanyRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecordId = IDL.Text;
  const Category = IDL.Variant({
    'hr' : IDL.Null,
    'finance' : IDL.Null,
    'other' : IDL.Null,
    'sales' : IDL.Null,
    'operations' : IDL.Null,
  });
  const CompanyRecord = IDL.Record({
    'id' : RecordId,
    'value' : IDL.Float64,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'category' : Category,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteRecord' : IDL.Func([RecordId], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(CompanyRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };